### ISSUE TITLE
Make all Github links reference a specific commit

### ISSUE THREAD

**Issue by Aaron1011** [0xAX/linux-insides#480]
Currently, many links to the Linux kernel source on Github use a ref of `master` in the URL. If the referenced file is later modified, the line offsets used in the link can become invalid.

To ensure that all links in the book remain valid, they should be modified to explicitly reference the latest commit (at the time of writing). For example, https://github.com/torvalds/linux/blob/249f1efd8e3d58f86469fc305b0eda39db18d7ce/arch/x86/boot/header.S#L292 should be used instead of https://github.com/torvalds/linux/blob/master/arch/x86/boot/header.S#L292.

Note: When viewing a file on Github, you can use the `y` keyboard shortcut to change the page's URL to reference the latest commit (as opposed to `master`).

**Comment by light2yellow** [comment]
Maybe a better solution would be to paste 3-5-10 line context directly into the book where a link exists, and then link just to the `master` version of the source file.

**Comment by 0xAX** [comment]
@Aaron1011 👍 for the issue. 

Yes. The biggest problem with the linux-insides is to hold it in actual state, because of fast speed of changing of the Linux kernel. I will try to update all parts of the books which falls behind the upstream kernel during the near time. But sometimes it is not easy deal. 

For now yes, links to upstream kernel source code may be replaced with links to specific commits. 

If somebody wants to help with this, PRs are welcome
