### ISSUE TITLE
Booting from Reset Vactor

### ISSUE THREAD

**Issue by sumitgemini** [0xAX/linux-insides#55]
I read your post it is really very informative. but i have some doubt.
I am trying to understand booting process.

1) how cpu know about physical ram and Bios rom?
2) what is reset vector and how can it save at 0xfffffff0 location beacuse ram is volatile memory.
3) Bios works in real mode where only 1 mb can access how does cpu access 0xfffffff0( above 1 mb code)?
4) how bios rom and ram maaped to each other?
5) what about if system has 1 gb ram then how cpu access 0xfffffff0 ram?

Thanks & Regards
~Sumit Gemini

**Comment by 0xAX** [comment]
@sumitgemini 

> 1) how cpu know about physical ram and Bios rom?

it's address hard-coded, so CPU knows about it after reset

> 2) what is reset vector and how can it save at 0xfffffff0 location because ram is volatile memory.

It's not in RAM. BIOS initializes RAM, so after reset CPU even can't work with RAM

> 3) Bios works in real mode where only 1 mb can access how does cpu access 0xfffffff0( above 1 mb code)?
> 4) how bios rom and ram mapped to each other?
> 5) what about if system has 1 gb ram then how cpu access 0xfffffff0 ram?

You can find some information here - http://www.coreboot.org/Developer_Manual/Memory_map about it + Minimal Boot Loader for Intel® Architecture (you can find link on it in the first part).

**Comment by sumitgemini** [comment]
Hi,

May I know what do you mean by this:-

"It's not in RAM. BIOS initializes RAM, so after reset CPU even can't work with RAM"

I am really confused with booting procedure.

Thanks & Regards
~Sumit Gemini

-----Original Message-----

**Comment by 0xAX** [comment]
> I am really confused with booting procedure.

Yes, there is many magic things before bootloader.

As i already wrote read the Minimal boot Loader for Intel Architecture manual and http://wiki.osdev.org/System_Initialization_%28x86%29

It must be helpful

**Comment by sumitgemini** [comment]
HI,

Thanks for this link, i read it and got what bios did.

But still there are some question that make me confused.

1) what is reset vector?
      I got this, reset vector is a address where "jump" instruction
reside. this jump instruction tells CPU to execute BIOS mapped memory code.

2) But where does reset vector reside?  is in RAM?  Ram is volatile, how
can RAM store any instruction?
 "http://www.embeddedlinux.org.cn/RTConforEmbSys/5107final/LiB0017.html
<http://www.embeddedlinux.org.cn/RTConforEmbSys/5107final/LiB0017.html>"
according to this link reset vector is a part of ROM. so it is confusing me.

3) if BIOS ROM copied reset vector at 0xfffffff0 then that is the purpose
of doing it? why is not directly jumped to 0xfffff (1 MB) area??
4) and if RAM is > 4GB, then how bios rom reached at address 0xfffffff0?
      for 4th question, my understanding is, when bios detected RAM, RAM is
divided into parts, and according to available ram, the part is maaped to
rom!! Am i in right?


And at last, May i know your name please?

Thanks & Regards
~Sumit Gemini

**Comment by 0xAX** [comment]
@sumitgemini Yes reset vector is just place in memory which stores jump instruction with address of the bios entry point.

>2) But where does reset vector reside? is in RAM? Ram is volatile, how can RAM store any instruction?

It's not in RAM, it is in ROM. After computer reseted RAM is clear and BIOS must check and initialize it. So it stores in ROM. CPU has hard-coded address of reset vector in it's `CS:IP` and it just extracts it from the ROM and execute it.

>3) if BIOS ROM copied reset vector at 0xfffffff0 then that is the purpose of doing it? why is not directly jumped to 0xfffff (1 MB) area??
4) and if RAM is > 4GB, then how bios rom reached at address 0xfffffff0? for 4th question, my understanding is, when bios detected RAM, RAM is divided into parts, and according to available ram, the part is maaped to rom!! Am i in right?

BIOS doesn't copies anything. Look CPU must know where to start, it must get address from the `CS:IP` and extract instruction from there. First instruction is a jump on the bios entry point. This hard-coded address name is `reset vector`. 

Forget about RAM for now :) RAM memory is not setup, VGA memory not even available and initialized. When we turn on computer, CPU starts in real mode but with one little difference: address lines 31-20 are high on reset until a `jmp` instruction is encountered, after it they will be low again. This is main reason how CPU can access  That's why we can't jump on the first megabyte right after reset. When RAM is ready, BIOS copies itself to it under 1 MB. 

> And at last, May i know your name please?

My name is Alex :)

**Comment by sumitgemini** [comment]
Dear Alex,

First of all thank you very much for help me to understand booting sequence.
I draw one image which is basis on my understanding.

[image: Inline image 3]


So is it clear picture of x86 point of view? I am taking 80386 processor
reference where reset vector size is 0xFFFFFFF0.


Following doubt still i have:-


   1. "address lines 31-20 are high on reset until a jmp instruction is
   encountered,"  real mode work with 0-19 bit (2^20 bit (1 MB)), if 20-31
   bit also enable then it will be 32 bit. so address 0xFFFFFFF0 is ROM
   address. Am i in right?
   2. if it is, then reset vector called jmp instruction which take CPU at
   address 0xFFFF0. is 0xFFFF0 ROM address or RAM address? as you stated
   BIOS detect and initialized RAM. when bios gets RAM then copy itself to
   there.
   if 0xFFFFF0 is RAM address then how can BOIS copy its contents into RAM
   because BIOS run after jmp instruction. so how does RAM address 0xFFFF0
   encounter by reset vector before bios run?


below image i got from net that made me confused. in this pic,4GB ram
showing and address 0xfffffff0 is mapped at the top of RAM physical memory.
But you said there is no ram until Bios detect ram. so how did reset vector
mapped to RAM at address 0xFFFFFFF0?





Please clear my doubt. I shall be very grateful for your help. I want to
write small loader so first i want basic. and want to know how to start
writing a boot loader.

Thanks  & Regards
~Sumit Gemini

**Comment by 0xAX** [comment]
@sumitgemini pink me in skype - `antikomdeveloper`, will try to explain there.

**Comment by sumitgemini** [comment]
Dear Alex,

Please find attached images.

Thanks & Regards
~Sumit Gemini
