### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by alexbarclay** [0xAX/linux-insides#57]
Is it possible to add a license that I can agree to before I submit a pull request?

**Comment by mikef5410** [comment]
I'm sorry ... I didn't submit a pull request ... or at least, I didn't mean to.

**Comment by 0xAX** [comment]
@alexbarclay hmm, I didn't plan to add license. Why do you care about it?

**Comment by tOkeshu** [comment]
Without a license this work in under a default copyright.

In theory this means no one has the right to copy or remix it.
Even contributions fall into a grey area where you can't even know who can do what with their work or the work of others (if you're not a specialized lawyer at least).

A license clarify that.

Because ultimately it's the choice of the initial authors, I won't suggest any license. But in case you need help to decide, I can provide advices from the point of view of a fellow developer :)

**Comment by TheCodeArtist** [comment]
Why is a license important? 
https://github.com/blog/1964-license-usage-on-github-com

Assuming you would want credit for your work and would have no objections to anyone (including yourself) making money out of this at some future point in time, a  "CC-BY" seems most appropriate.

For more choices visit http://choosealicense.com/

**Comment by 0xAX** [comment]
@TheCodeArtist yes, you're fully rightю I have long been thinking about license for linux-insides, but can't find time to it. Seems the time to add license.

**Comment by 0xAX** [comment]
Added information about licens to the README.md
