### ISSUE TITLE
Why there is a semicolon between rep and movsl, aka, "rep; movsl" in copy.S

### ISSUE THREAD

**Issue by Jekton** [0xAX/linux-insides#664]
Hi, I'm reading your [post](https://github.com/0xAX/linux-insides/blob/master/Booting/linux-bootstrap-2.md) about the implementation of `memcpy`:
```asm
GLOBAL(memcpy)
	pushw	%si
	pushw	%di
	movw	%ax, %di
	movw	%dx, %si
	pushw	%cx
	shrw	$2, %cx
	rep; movsl
	popw	%cx
	andw	$3, %cx
	rep; movsb
	popw	%di
	popw	%si
	retl
ENDPROC(memcpy)
```
Isn't the semicolon is assembly language stands a comment? but if the `movsl, movsb` is commented out, how the `rep` knows the bytes to copy at a time?

**Comment by mudongliang** [comment]
I think you are right. `rep` cannot verify which instruction it executes. I guess "rep; movsl" equals "rep movsl". @0xAX why is there a semicolon";" after `rep`?

**Comment by mudongliang** [comment]
I think I have figured out where the problem is. The assembly instructions in Linux kernel are in AT&T syntax. In AT&T, the comment symbol is not ";", but "#". Why do you get confused? Because in Intel Assembly instruction, the comment is ";".

And to confirm this statement, I did a small test in the following step:
1. create one `test.S` with instructions in AT&T syntax;
```
.global _start

.text
_start:
        movl  $4, %eax
        movl  $1, %ebx
        movl  $msg, %ecx
        movl  $len, %edx
        int   $0x80

        movl  $1, %eax ; movl $10, %ebx
        movl  $0, %ebx
        int   $0x80
.data
msg:
        .ascii  "Hello, world!\n"
        len =   . - msg
```
2. if ";" is working as comment, in executable binary, we cannot find "movl $10, %ebx".
3. when we get the executable binary with `as` and `ld`, we find this instruction in the binary:
```
Disassembly of section .text:

00000000004000b0 <_start>:
  4000b0:	b8 04 00 00 00       	mov    $0x4,%eax
  4000b5:	bb 01 00 00 00       	mov    $0x1,%ebx
  4000ba:	b9 d7 00 60 00       	mov    $0x6000d7,%ecx
  4000bf:	ba 0e 00 00 00       	mov    $0xe,%edx
  4000c4:	cd 80                	int    $0x80
  4000c6:	b8 01 00 00 00       	mov    $0x1,%eax
-->  4000cb:	bb 0a 00 00 00       	mov    $0xa,%ebx
  4000d0:	bb 00 00 00 00       	mov    $0x0,%ebx
  4000d5:	cd 80                	int    $0x80
```

**Comment by mudongliang** [comment]
For more detailed differences between Intel Assembly and AT&T Assembly, you could refer to https://philipchungtech.weebly.com/x86-asm-intel-to-att.html

**Comment by Jekton** [comment]
Thanks, it helps a lot.
